### ISSUE TITLE
Add reverse calculation for speed and pace

### ISSUE THREAD

**Issue by Segelzwerg** [Segelzwerg/SportToolBox#70]
- [x]  distance, speed -> time done #79 
- [x] speed, time -> distance #88 

- [x] distance, pace -> time done #81 

- [x] pace, time -> distance #88

**Comment by Segelzwerg** [comment]
done
